apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-api
spec:
  type: LoadBalancer
  selector:
    app: test-api
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 5000